# 1. Aesthetics
set-option -g status-position top
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# 2. Vim Keybindings for Copy Mode
# Use 'v' to begin selection and 'y' to yank (requires tmux-yank plugin)
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# 3. Mouse Support (for those lazy moments)
set -g mouse on

# 4. Prettier Status Bar (Catppuccin tweaks)
set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_uptime}"

