#monitor definition
monitor=DP-4,1920x1080@143.85,0x0,1,transform,1
monitor=DP-1,2560x1440@165.00,1080x0,1.25
monitor=eDP-1,3072x1920@120.00,3128x0,2

$mainMonitor = DP-1
$secondMonitor = DP-4
$thirdMonitor = eDP-1

# workspace rules
workspace = 1, monitor:$mainMonitor, layout:scrolling, default:true, persistent:true
workspace = 2, monitor:$mainMonitor
workspace = 3, monitor:$mainMonitor

workspace = 4, monitor:$secondMonitor
workspace = 5, monitor:$secondMonitor
workspace = 6, monitor:$secondMonitor

workspace = 7, monitor:$thirdMonitor
workspace = 8, monitor:$thirdMonitor
workspace = 9, monitor:$thirdMonitor
